[tool.poetry]
name = "recs"
version = "0.1.0"
description = "🎬 Record everything automatically 🎬"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dtyper = "^2.1.0"
numpy = "^1.25.1"
pyaudio = "^0.2.13"
rich = "^13.5.2"
sounddevice = "^0.4.6"
soundfile = "^0.12.1"
threa = "^0.3.0"
typer = "^0.9.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
mypy = "^1.4.1"
pytest = "^7.3.1"
ruff = "^0.0.280"
tdir = "^1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true

[tool.black]
skip-string-normalization = true
target-version = ["py311"]

[tool.isort]
profile = "black"
